kind: Service
apiVersion: v1
metadata:
  name: boissibook-scrapper
spec:
  selector:
    run: boissibook-scrapper
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer